ci: Fix conda CI
During the CI build, we encountered the following waring:
```
WARNING (gnuradio-polarwrap,lib/libgnuradio-polarwrap.so.gb89dd16): Needed DSO lib/libPolarCode.so found in ['polar-codes']
WARNING (gnuradio-polarwrap,lib/libgnuradio-polarwrap.so.gb89dd16): .. but ['polar-codes'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
```
Later on, `polar-codes` is not installed during the test build. Thus,
this happens:
```
import: 'polarwrap'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/gnuradio-polarwrap_1675074542083/_test_env_{CUT SHORT}/lib/python3.11/site-packages/polarwrap/__init__.py", line 17, in <module>
    from .polarwrap_python import *
ImportError: libPolarCode.so: cannot open shared object file: No such file or directory
```
Hopefully, by adding `polar-codes` to `requirements/run` fixes the
problem.

Signed-off-by: Johannes Demel <demel@ant.uni-bremen.de>